### ISSUE TITLE
Error indicator not clearing on some situations

### ISSUE THREAD

**Issue by yakubbaev** [inmite/android-validation-komensky#13]
My environment:
* compile ('eu.inmite.android.lib:android-validation-komensky:0.9.2')
* Using live validation on fragments

Case A: 
Have EditText with rule MaxLength(3). 
1. Enter 4 symbols. 
2. Change focus. 
=> Error indicator pops up
3. Remove one symbol. Now there're 3 symbols on EditText
4. Change focus
Expected result: Error indicator cleared
Actual result: Error indicator stays as was.

However, error indicator gets cleared in following case:
Case B:
E.g have EditText with rule MinLength(2);
1. Enter 1 symbol
2. Change focus
=> Error indicator pops up
3. Enter another symbol. Now there're 2 symbols on EditText
4. There's no step 4. No need to change focus.
Result: Error indicator cleared as expected.

As I understood, the reason is TextView automatically clears its error indicator when user inputs some text.
After more digging into komensky lib, I figured out that you are not handling  at all case when validation succeeds on FormValidator.onGlobalFocusChanged method. I would like to hear your thoughts on this issue. Thanks!

**Comment by tomas-vondracek** [comment]
Well, that's a bug :) It was fixed by #10

Thank you.
