### ISSUE TITLE
Regular fragments support?

### ISSUE THREAD

**Issue by tonnyavery** [inmite/android-validation-komensky#14]
I'm not using support.v4.Fragment in my project - I reference v13 support library and use regular SDK Fragment class as the base for all my fragments.
Passing that fragments class instance to validate function doens't work - it requires either Activity or support.v4.Fragment.
Would be good to be able to use library without support.v4 at all.

**Comment by mindrunner** [comment]
Is there any plan to change this? What is the actual reason for that? Any workarounds?
