### ISSUE TITLE
build failed upon adding library

### ISSUE THREAD

**Issue by Aexyn** [inmite/android-validation-komensky#20]
As soon as  I add 

> compile 'eu.inmite.android.lib:android-validation-komensky:0.9.2'

in my gradle and build it , it gives this error:

> Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     E:\Aman\sdk\build-tools\21.1.2\dx.bat --dex --no-optimize --output E:\Aman\Workspace\I2I\app\build\intermediates\dex\debug --input-list=E:\Aman\Workspace\I2I\app\build\intermediates\tmp\dex\debug\inputList.txt
> Error Code:
>     2
> Output:
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
>         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
>         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
>         at com.android.dx.command.dexer.Main.run(Main.java:246)
>         at com.android.dx.command.dexer.Main.main(Main.java:215)
>         at com.android.dx.command.Main.main(Main.java:106)

I dont know why this error or which other library it is conflicting with, So I here are other libraries in my project:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:recyclerview-v7:21.0.3'
    compile 'com.android.support:cardview-v7:21.0.3'
    compile 'com.google.android.gms:play-services-location:6.5.87'

    compile 'com.squareup.okhttp:okhttp:2.1.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.1.0'
    compile 'com.squareup.retrofit:retrofit:1.8.0'
    compile 'com.jakewharton:butterknife:6.0.0'
    compile 'com.google.code.gson:gson:2.3.1'

    compile 'com.nispok:snackbar:2.5.2'
    compile 'eu.inmite.android.lib:android-validation-komensky:0.9.2'


}
```

**Comment by hosek** [comment]
I can confirm, that the problem is still here

**Comment by tomas-vondracek** [comment]
Yes, it will go away in next release. Until then, you can try snapshot version: https://oss.sonatype.org/content/repositories/snapshots/eu/inmite/android/lib/android-validation-komensky/)
