### ISSUE TITLE
Don't work @Condition with android.app.Fragment

### ISSUE THREAD

**Issue by maimuzo** [inmite/android-validation-komensky#24]
in FormValidator.evaluateCondition():

		if (target instanceof Activity) {
			conditionView = ((Activity) target).findViewById(viewId);
		} else if (target instanceof Fragment) {
			conditionView = ((Fragment) target).getView().findViewById(viewId);
		} else if (target instanceof View) {
			conditionView = ((View) target).findViewById(viewId);
		} else {
			throw new FormsValidationException("unknown target " + target);
		}

this class imports android.support.v4.app.Fragment

**Comment by tomas-vondracek** [comment]
fixed by 483c72c050a8c020c83094bad6de505150738d20
