### ISSUE TITLE
LiveValidation: validationComplete not called if validation successful

### ISSUE THREAD

**Issue by AndreRoss** [inmite/android-validation-komensky#27]
The error is in the FormValidator you should change:

if (validationFail != null && callback != null) {
						// we have a failed validation
						this.callback.validationComplete(false, Collections.singletonList(validationFail));
					}

to 

if (validationFail != null && callback != null) {
            // we have a failed validation
            this.callback.validationComplete(false, Collections.singletonList(validationFail));
        }else if(callback != null){
            this.callback.validationComplete(true, null);
        }

**Comment by tomas-vondracek** [comment]
this has been fixed by 2a1c5b6b17bf1383ec8f86c7dcb7db4038700c7b
