### ISSUE TITLE
can't  use in viewholder

### ISSUE THREAD

**Issue by palize** [inmite/android-validation-komensky#28]
I usually like it in my viewholder. But it does not seem possible in viewholder.

static class creditViewHolder {
        @InjectView(R.id.txtcredit)
        TextView txtcredit;
        @InjectView(R.id.btncredit)
        Button btncredit;

        @NotEmpty(messageId = R.string.creditnotempty)
        @MinValue(value = 1, messageId = R.string.creditminvalue)
        @InjectView(R.id.editprice)
        EditText editprice;
        @InjectView(R.id.btnok)
        Button btnok;
        @InjectView(R.id.pricelayout)
        LinearLayout pricelayout;

        creditViewHolder(View view) {
            ButterKnife.inject(this, view);
        }
}

how do i validate viewholder?

**Comment by tomas-vondracek** [comment]
this shouldn't be a problem, just call
```
FormValidator.validate(context, viewholder, callback)
```
