### ISSUE TITLE
Android Studio build error - Multiple dex files define Landroid/support/v4/

### ISSUE THREAD

**Issue by newstarbka** [inmite/android-validation-komensky#29]
I am unable to build my project in Android Studio. I get the following error:
Multiple dex files define Landroid/support/v4/

**Comment by hosek** [comment]
Hi,
I think you hit this issue:
https://github.com/inmite/android-validation-komensky/issues/20

**Comment by tomas-vondracek** [comment]
yes, see #20 for solution
