### ISSUE TITLE
Project Unmaintained?

### ISSUE THREAD

**Issue by mindrunner** [inmite/android-validation-komensky#31]
It looks pretty much that this library got some issues and is no longer maintained. Who is actively using this? Who is satisfied? Also there are more than 50 forks of this project? Is there any more active version?

**Comment by tomas-vondracek** [comment]
We are going to release bugfix update soon. It's taking too long, I know, but we are not abandoning the project.

**Comment by mindrunner** [comment]
Yay, thats good to hear! Just wanted to know, because there are so may abandoned libs out there...
