### ISSUE TITLE
Gradle: Failed to resovle

### ISSUE THREAD

**Issue by vijaemanlapaz** [inmite/android-validation-komensky#32]
Hi it says Gradle: Failed to resolve

i have the following in my gradle script

repositories {
    mavenCentral()
}

dependencies {
    compile 'eu.inmite.android.lib:android-validation-komensky:0.9.2'
}

**Comment by tomas-vondracek** [comment]
please, try new version
```groovy
compile 'eu.inmite.android.lib:android-validation-komensky:0.9.4@aar'
```
