### ISSUE TITLE
Custom adapter for Spinner

### ISSUE THREAD

**Issue by beyondsanity** [inmite/android-validation-komensky#34]
Hi,

i'm working on a form that use a custom spinner adapter.
I'm trying to define and bind a custom IFieldAdapter for validating this field without success, debugging shows that Komensky always uses the default SpinnerAdapter.

FormValidator.registerViewAdapter(Spinner.class, SpinnerValidatorAdapter.class);
FormValidator.validate(_this, new SimpleErrorPopupCallback(context));

Am i doing something wrong?

**Comment by tomas-vondracek** [comment]
It was a bug and it has been fixed in 11a2d5fc0f5f97b686e15ddca8079f24f8be844d, please try new version 0.9.4.

Thank you.
